// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace GrocAPI.Migrations
{
    [DbContext(typeof(HoneyDoContext))]
    [Migration("20171231070516_onlist")]
    partial class onlist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrocAPI.Models.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("List");

                    b.HasDiscriminator<string>("Discriminator").HasValue("List");
                });

            modelBuilder.Entity("GrocAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aisle");

                    b.Property<bool>("Complete");

                    b.Property<int>("GroceryListId");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<bool>("OnList");

                    b.HasKey("Id");

                    b.HasIndex("GroceryListId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("GrocAPI.Models.GroceryList", b =>
                {
                    b.HasBaseType("GrocAPI.Models.List");


                    b.ToTable("GroceryList");

                    b.HasDiscriminator().HasValue("GroceryList");
                });

            modelBuilder.Entity("GrocAPI.Models.Product", b =>
                {
                    b.HasOne("GrocAPI.Models.GroceryList")
                        .WithMany("Products")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
